remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Mac Admins Open Source
github:
  is_project_page: false
url: https://macadmins.github.io
navigation:
  - name: Home
    link: /
  - name: Project Onboarding
    link: /project-onboarding/
